---
name: 'wolfictl-lint'
description: |
  Wolfictl Lint and Lint yam.

inputs:
  run_wolfictl_lint:
    description: |
      Run only wolfictl lint.
    required: false
    default: 'true'
  run_wolfictl_lint_yam:
    description: |
      Run only wolfictl lint yam.
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Lint
      if: ${{ inputs.run_wolfictl_lint == 'true' }}
      id: lint
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:2241bf7eb8adb05fa2860e4cfb0ba039c5cefe979286f9fb47de0035db57f2a2
      with:
        entrypoint: wolfictl
        args: lint --skip-rule no-makefile-entry-for-package

    - name: Enforce YAML formatting
      if: ${{ inputs.run_wolfictl_lint_yam == 'true' }}
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:2241bf7eb8adb05fa2860e4cfb0ba039c5cefe979286f9fb47de0035db57f2a2
      with:
        entrypoint: wolfictl
        args: lint yam
