---
name: 'wolfictl-check-updates'
description: |
  Wolfictl Check Updates.

inputs:
  token:
    description: |
      GitHub Token or OctoSts token.
    required: false
    default: ""
  changed_files:
    description: |
      List of changed files to check.
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: wolfictl-check-updates
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:2241bf7eb8adb05fa2860e4cfb0ba039c5cefe979286f9fb47de0035db57f2a2
      with:
        entrypoint: wolfictl
        args: check update ${{ inputs.changed_files }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
